steps:
- name: 'gcr.io/cloud-builders/golang-project'
  args: ['superproxy', '--tag=eu.gcr.io/$PROJECT_ID/superproxy:$TAG_NAME']
  env: ['PROJECT_ROOT=superproxy']
images: ['eu.gcr.io/$PROJECT_ID/superproxy']