steps:
- name: 'gcr.io/cloud-builders/golang-project'
  args: ['$PROJECT_ROOT', '--tag=eu.gcr.io/$PROJECT_ID/superproxy:$TAG_NAME']
  env: ['PROJECT_ROOT=github.com/stugotech/superproxy']
images: ['eu.gcr.io/$PROJECT_ID/superproxy']